version: '2'

services:
  app:
    env_file: ./docker/environments/.env.app.production
    restart: always
    volumes:
      - ./public:/data/src/public
  db:
    restart: always
    env_file: ./docker/environments/.env.db.production
  web:
    restart: always
    volumes:
      - ./public:/data/src/public
