version: '2'

services:
  app:
    env_file: .env.web.production
    restart: always
    volumes:
      - ./public:/data/src/public
  db:
    restart: always
    env_file: .env.db.production
  web:
    restart: always
    volumes:
      - ./public:/data/src/public
