version: '2'

services:
  app:
    build: .
    depends_on:
      - db
    env_file: .env.web.development
    links:
      - db
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7.17
    env_file: .env.db.development
    volumes:
      - db_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"
volumes:
  db_data:
